### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by alecive** [ScazLab/baxter_tictactoe#6]
This issue is to keep track of the things we should do at some point in the future:
- [x] Create a single-package repo (see https://github.com/ScazLab/baxter_tictactoe/issues/5 )
- [x] Automatic perception of board cell/board boundaries see #10 
- [x] Move Baxter's right arm away from camera's POV upon launching tictactoe.launch (currently done manually)
- [x] Move from a set of predefined movements to a proper Inverse Kinematics algorithm (for the left arm)
- [x] Feedback in event that Baxter does not successfully pick up tile 
- [x] Disable perception when Baxter is making move (screen shows 'ghost' red tiles due to camera interpreting Baxter's left arm as red tiles)
- [x] Move vacuum gripper to tile position (currently tiles' position must be manually calibrated to Baxter's arm movements)
- [x] Detect which tile Baxter is using (currently Baxter assumes use of blue tile by default)
- [x] Adapt the vacuum gripper software to the new vacuum gripper (see https://github.com/ScazLab/baxter_collaboration/issues/5 )
- [x] Fix img_screen node _Error message: "/home/baxter/ros_ws/src/baxter_examples/scripts/xdisplay_image.py", line 36, in <module> import cv2 ImportError: libopencv_core.so.3.1: cannot open shared object file: No such file or directory_
- [x] Move from `festival` to `svox_tts` (from here https://github.com/ScazLab/svox_tts )

**Comment by alecive** [comment]
@JohnAmadeo in order for you to start getting used to the IK service, you might start addressing item 3 in this list that should be pretty easy to do at this point.

**Comment by alecive** [comment]
The vacuum gripper issue will be taken care of in https://github.com/ScazLab/baxter_collaboration/issues/5
